massey-effect-matthews-mages/Models/Friend.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massey_effect_matthews_mages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public string User { get; set; }
        public string Friend1 { get; set; }
    }
}

massey-effect-matthews-mages/Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massey_effect_matthews_mages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Message1 { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}

massey-effect-matthews-mages/Controllers/FriendController.cs
using massey_effect_matthews_mages.DataAL;
using massey_effect_matthews_mages.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace massey_effect_matthews_mages.Controllers
{
    [Authorize]
    public class FriendController : Controller
    {
        [HttpGet]
        public ActionResult ViewMessage(int messageId)
        {
            IDAL DAL = new DBDataAL();
            string Name = User.Identity.Name;
            User user = DAL.GetUser(Name);
            Message message = DAL.GetMessagesFor(user).Where(m => m.Id == messageId).ToList().First();
            return View("Message", message);
        }

        [HttpPost]
        public ActionResult DeleteMessage(int messageId)
        {
            IDAL DAL = new DBDataAL();
            string Name = User.Identity.Name;
            DAL.RemoveMessage(messageId);

            FriendData data = new FriendData(Name);
            return View("~/Views/Web/Friends.cshtml", data);
        }

        [HttpPost]
        public ActionResult SendMessage(Message message)
        {
            IDAL DAL = new DBDataAL();
            DAL.CreateMessage(message);

            string Name = User.Identity.Name;
            FriendData data = new FriendData(Name);
            return View("~/Views/Web/Friends.cshtml", data);
        }

        [HttpPost]
        public ActionResult NewMessage(string friend)
        {
            IDAL DAL = new DBDataAL();
            DateTime dt = DateTime.Now;
            byte[] bytes = BitConverter.GetBytes(dt.Ticks);
            Message message = new Message();
            message.Sender = User.Identity.Name;
            message.Receiver = friend;
            message.TimeStamp = bytes;
            return View(message);
        }

        //view friend profile

        [HttpPost]
        public ActionResult RemoveFriend(string friend)
        {
            string Name = User.Identity.Name;

            IDAL DAL = new DBDataAL();
            DAL.RemoveFriend(Name, friend);

            FriendData data = new FriendData(Name);
            return View("~/Views/Web/Friends.cshtml", data);
        }

        [HttpPost]
        public ActionResult AcceptFriendRequest(string sender)
        {
            string currentUser = User.Identity.Name;
            IDAL DAL = new DBDataAL();

            User user = DAL.GetUser(currentUser);

            IEnumerable<string> friends = DAL.GetFriends(user).ToList();
            if(!friends.Contains(sender))
            {
                DAL.AddFriend(currentUser, sender);
            }

            IEnumerable<FriendRequest> requests = DAL.GetFriendRequests(user).Where(r => r.Sender == sender);
            IEnumerable<FriendRequest> requests2 = DAL.GetFriendRequests(DAL.GetUser(sender)).Where(r => r.Sender == currentUser);
            IEnumerable<FriendRequest> fullList = requests.Concat(requests2);
            foreach (FriendRequest req in fullList)
            {
                DAL.RemoveFriendRequest(req);
            }

            FriendData data = new FriendData(currentUser);
            return View("~/Views/Web/Friends.cshtml", data);
        }

        [HttpPost]
        public ActionResult DenyFriendRequest(string sender)
        {
            string currentUser = User.Identity.Name;

            IDAL DAL = new DBDataAL();
            User user = DAL.GetUser(currentUser);
            FriendRequest fr = DAL.GetFriendRequests(user).Where(r => r.Sender == sender).ToList().First();
            DAL.RemoveFriendRequest(fr);
            
            FriendData data = new FriendData(currentUser);
            return View("~/Views/Web/Friends.cshtml", data);
        }
        
        [HttpGet]
        public ActionResult Search(string name)
        {
            string currentUser = User.Identity.Name;

            FriendData data = new FriendData(currentUser);
            data.SearchFor(name);

            return View("~/Views/Web/Friends.cshtml", data);
        }

        [HttpPost]
        public ActionResult RequestFriend(string name)
        {
            string currentUser = User.Identity.Name;

            IDAL DAL = new DBDataAL();
            User user = DAL.GetUser(name);
            try
            {
                FriendRequest requests = DAL.GetFriendRequests(user).Where(x => x.Sender == currentUser).First();
            }
            catch(Exception) //if null catch explosion
            {
                FriendRequest fr = new FriendRequest();
                fr.Receiver = name;
                fr.Sender = currentUser;
                DAL.CreateFriendRequest(fr);
            }

            FriendData data = new FriendData(currentUser);

            return View("~/Views/Web/Friends.cshtml", data);
        }
    }
}

massey-effect-matthews-mages/Views/Friend/ActiveFriendRequests.cshtml
@using massey_effect_matthews_mages.Models
@model IEnumerable<FriendRequest>

<div class="ldiv boxdiv">
    <h1 class="socialheader">Active Friend Requests</h1>
    <br />
    <div class="activefriendrequestsdiv">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (FriendRequest fr in Model)
            {
                <div class="socialline">
                    <p class="socialp">@fr.Sender</p>

                    <form class="socialbutton" action="~/Friend/DenyFriendRequest" method="post">
                        <button class="socialimage" name="sender" value="@fr.Sender" type="submit"><img src="~/Content/Images/Deny.png" /></button>
                    </form>

                    <form class="socialbutton" action="~/Friend/AcceptFriendRequest" method="post">
                        <button class="socialimage" name="sender" value="@fr.Sender" type="submit"><img src="~/Content/Images/Approve.png" /></button>
                    </form>
                </div>
            }
        }
    </div>
</div>

massey-effect-matthews-mages/Views/Friend/FriendsList.cshtml
@model IEnumerable<string>

<div class="rdiv boxdiv">
    <h1 class="socialheader">Friends List</h1>
    <br />
    <div class="friendslistdiv">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (string friend in Model)
            {
                <div class="socialline">
                    <p class="socialp">@friend</p>

                    <form class="socialbutton" action="~/Friend/RemoveFriend" method="post">
                        <button class="socialimage" name="friend" value="@friend" type="submit"><img src="~/Content/Images/Delete.png" /></button>
                    </form>

                        <a href="\FProfile\@friend"><button class="socialimage"><img src="~/Content/Images/View.png" /></button></a>

                    <form class="socialbutton" action="~/Friend/NewMessage" method="post">
                        <button class="socialimage" name="friend" value="@friend" type="submit"><img src="~/Content/Images/Message.png" /></button>
                    </form>
                </div>
            }
        }
    </div>
</div>

massey-effect-matthews-mages/Views/Friend/Message.cshtml
@using massey_effect_matthews_mages.Models
@model Message

@{
    ViewBag.StyleSheet = "KurtsSheet.css";
}

<section id="content">
    <div class="messagebody">
        <h2>To: @Model.Receiver</h2>
        <h2>From: @Model.Sender</h2>
        <hr />
        <p>@Model.Message1</p>     
        <a href="~/Web/Friends">Return to Friends page.</a>   
    </div>

    <div class="coolio" id="bot">
    </div>
</section>

massey-effect-matthews-mages/Views/Friend/Messages.cshtml
@using massey_effect_matthews_mages.Models
@model IEnumerable<Message>

<div class="ldiv boxdiv">
    <h1 class="socialheader">Messages</h1>
    <br />
    <div class="messagesdiv">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (Message m in Model)
            {
                string name = m.Sender;
                if(m.Sender.ToString().Length > 10)
                {
                    name = name.Substring(0, 10) + "...";
                }
                string message = m.Message1;
                if(message.Length > 15)
                {
                    message = m.Message1.Substring(0, 10)+"...";
                }
                <div class="socialline">
                    <p class="socialp">@name : @message</p>

                    <form class="socialbutton" action="~/Friend/DeleteMessage" method="post">
                        <button class="socialimage" name="messageId" value="@m.Id" type="submit"><img src="~/Content/Images/Delete.png" /></button>
                    </form>

                    <form class="socialbutton" action="~/Friend/ViewMessage" method="get">
                        <button class="socialimage" name="messageId" value="@m.Id" type="submit"><img src="~/Content/Images/View.png" /></button>
                    </form>
                </div>
            }
        }
    </div>
</div>

massey-effect-matthews-mages/Views/Friend/NewMessage.cshtml
@model massey_effect_matthews_mages.Models.Message
@{
    ViewBag.StyleSheet = "KurtsSheet.css";
}

<section id="content">
    <div class="newmessagebody">
        <h2>To: @Model.Receiver</h2>
        <h2>From: @Model.Sender</h2>
        @using (Html.BeginForm("SendMessage", "Friend", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id);
            @Html.HiddenFor(x => x.TimeStamp);
            @Html.HiddenFor(x => x.Receiver)
            @Html.HiddenFor(x => x.Sender)
            @Html.TextAreaFor(x => x.Message1, new { @class = "messagebox" });  

            <input type="submit" class="sendmessagebutton" value="Send" />
        }
        <a href="~/Web/Friends">Cancel</a>
    </div>

    <div class="coolio" id="bot">
    </div>
</section>

massey-effect-matthews-mages/Views/Friend/NotFriends.cshtml
@using massey_effect_matthews_mages.Models
@model IEnumerable<string>

<div class="rdiv boxdiv">
    <h1 class="socialheader">Find Some Friends</h1>
    <br />
    <div class="notfriendsdiv">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (string user in Model)
            {
                <div class="socialline">
                    <p class="socialp">@user</p>
                    <form class="socialbutton" action="~/Friend/RequestFriend" method="post">
                        <button class="socialimage" name="name" value="@user" type="submit"><img src="~/Content/Images/Add.png" /></button>
                    </form>
                </div>
            }
        }
    </div>
</div>